apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: Local-PV
  namespace: nginx  
spec:  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
