apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicasets
  namespace: nginx
spec:
  replicas: 2   
  selector:
    matchLabels:   
      app: nginx
  template:
    metadata:
      name: nginx-res-pod
      labels:  
        app: nginx    


    # spec: if need then we can use it.
    #   containers:
    #     - name: nginx
    #       image: nginx:latest
    #       ports:
    #         - containerPort: 80

# kubectl apply -f replicaset.yaml        