kind: sercret
apiVersion: v1  
metadata:
  name: mysql-secret
  namespace: mysql-database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
  MYSQL_USER: bXl1c2Vy
  MYSQL_PASSWORD: bXl1c2VycGFzc3dvcmQ=
