kind: ServiceAccount
apiVersion: v1
metadata:
  name: apache-user
  namespace: apache 


# kubectl auth can-i get pods -n apache
# kubectl aut can-i get pods -n apache --as=apache-user
# kubectl auth can-i create deployments -n apache --as=apache-user  